[package]
name = "chrono-engine"
version = "0.1.0"
authors = ["Dylan Ede <dylanede@googlemail.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3.25"

[dependencies]
chrono-engine-sys = { path = "chrono-engine-sys", version = "0.1.0" }
libc = "0.2.8"
